In [1]:
# https://ru.wikipedia.org/wiki/%D0%A3%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%92%D0%B0%D0%BD-%D0%B4%D0%B5%D1%80-%D0%92%D0%B0%D0%B0%D0%BB%D1%8C%D1%81%D0%B0
"https://ru.wikipedia.org/wiki/Уравнение_Ван-дер-Ваальса"

<class 'SyntaxError'>: invalid syntax (<ipython-input-1-85b6a692186c>, line 2)

In [2]:
"β"

'β'

In [3]:
"😊"

'😊'

In [9]:
"\u03B2"

'β'

In [13]:
list("β😊") # mylist[0]

['β', '😊']

In [14]:
b"example"

b'example'

In [15]:
b"пример"

<class 'SyntaxError'>: bytes can only contain ASCII literal characters (<ipython-input-15-3608fa429aea>, line 1)

In [16]:
get(url)

<class 'NameError'>: name 'get' is not defined

In [17]:
%pip install requests

In [2]:
import requests

In [4]:
url = (
    "https://ru.wikipedia.org"
    "/wiki"
    "/Уравнение_Ван-дер-Ваальса"
)
url

'https://ru.wikipedia.org/wiki/Уравнение_Ван-дер-Ваальса'

In [5]:
requests.get(url)

In [7]:
resp = requests.get(url)
resp

In [11]:
print(*resp.headers.items(), sep="\n")

('cache-control', 'private, s-maxage=0, max-age=0, must-revalidate, no-transform')
('content-language', 'ru')
('content-length', '33790')
('content-type', 'text/html; charset=UTF-8')
('last-modified', 'Thu, 26 Feb 2026 12:44:47 GMT')

In [13]:
resp.content[:50]

b'<!DOCTYPE html>\n<html class="client-nojs skin-them'

In [14]:
resp.content

b'<!DOCTYPE html>\n<html class="client-nojs skin-theme-clientpref-thumb-standard" lang="ru" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0 \xe2\x80\x94 \xd0\x92\xd0\xb8\xd0\xba\xd0\xb8\xd0\xbf\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f</title>\n<script>(function(){var className="client-js skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )ruwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":[",\\t.","\xc2\xa0\\t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","\xd1\x8f\xd0\xbd\xd0\xb2\xd0\xb0\xd1\x80\xd1\x8c","\xd1\x84\xd0\xb5\xd0\xb2\xd1\x80\xd0\xb0\xd0\xbb\xd1\x8c","\xd0\xbc\xd0\xb0\xd1\x80\xd1\x82","\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbb\xd1\x8c","\xd0\xbc\xd0\xb0\xd0\xb9","\xd0\xb8\xd1\x8e\xd0\xbd\xd1\x8c","\xd0\xb8\xd1\x8e\xd0\xbb\xd1\x8c","\xd0\xb0\xd0\xb2\xd0\xb3\xd1\x83\xd1\x81\xd1\x82","\xd1\x81\xd0\xb5\xd0\xbd\xd1\x82\xd1\x8f\xd0\xb1\xd1\x80\xd1\x8c","\xd0\xbe\xd0\xba\xd1\x82\xd1\x8f\xd0\xb1\xd1\x80\xd1\x8c","\xd0\xbd\xd0\xbe\xd1\x8f\xd0\xb1\xd1\x80\xd1\x8c","\xd0\xb4\xd0\xb5\xd0\xba\xd0\xb0\xd0\xb1\xd1\x80\xd1\x8c"],"wgRequestId":"77703163-bfd2-4cca-83d3-512df387fc57","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5_\xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0","wgTitle":"\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0","wgCurRevisionId":151838280,"wgRevisionId":151838280,"wgArticleId":635642,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd1\x8b, \xd0\xb8\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd1\x83\xd1\x8e\xd1\x89\xd0\xb8\xd0\xb5 \xd0\xb2\xd0\xbe\xd0\xbb\xd1\x88\xd0\xb5\xd0\xb1\xd0\xbd\xd1\x8b\xd0\xb5 \xd1\x81\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb8 ISBN","\xd0\xa4\xd0\xb8\xd0\xb7\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xbe\xd0\xbd\xd1\x8b \xd0\xb8 \xd1\x83\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f","\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd1\x81\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x8f\xd0\xbd\xd0\xb8\xd1\x8f","\xd0\xa5\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xbe\xd0\xbd\xd1\x8b \xd0\xb8 \xd1\x83\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f","\xd0\x98\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xbe\xd0\xbd\xd1\x8b \xd0\xb8 \xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd0\xbb\xd0\xb0"],"wgPageViewLanguage":"ru","wgPageContentLanguage":"ru","wgPageContentModel":"wikitext","wgRelevantPageName":"\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5_\xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0","wgRelevantArticleId":635642,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"accuracy":{"levels":1}}},"wgStableRevisionId":151838280,"wgConfirmEditCaptchaNeededForGenericEdit":false,"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"ru","pageLanguageDir":"ltr","pageVariantFallbacks":"ru"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":20000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":true,"wgVector2022LanguageInHeader":false,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q254329","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgGEUseTestKitchenExtension":true,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]},"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};\nRLSTATE={"ext.gadget.common-site":"ready","ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","ext.math.styles":"ready","skins.vector.styles.legacy":"ready","jquery.tablesorter.styles":"ready","ext.flaggedRevs.basic":"ready","mediawiki.codex.messagebox.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","ext.math.polyfills","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.legacy.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.flaggedRevs.advanced","ext.gadget.collapserefs","ext.gadget.directLinkToCommons","ext.gadget.referenceTooltips","ext.gadget.edittop","ext.gadget.navboxDefaultGadgets","ext.gadget.markadmins","ext.gadget.wikibugs","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.compactlinks","ext.uls.interface","ext.cx.eventlogging.campaigns","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession","ext.xLab","ext.testKitchen"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n}];});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=ru&amp;modules=ext.cite.styles%7Cext.flaggedRevs.basic%7Cext.math.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cjquery.tablesorter.styles%7Cmediawiki.codex.messagebox.styles%7Cskins.vector.styles.legacy%7Cwikibase.client.init&amp;only=styles&amp;skin=vector">\n<script async="" src="/w/load.php?lang=ru&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector"></script>\n<meta name="ResourceLoaderDynamicStyles" content="">\n<link rel="stylesheet" href="/w/load.php?lang=ru&amp;modules=ext.gadget.common-site&amp;only=styles&amp;skin=vector">\n<link rel="stylesheet" href="/w/load.php?lang=ru&amp;modules=site.styles&amp;only=styles&amp;skin=vector">\n<noscript><link rel="stylesheet" href="/w/load.php?lang=ru&amp;modules=noscript&amp;only=styles&amp;skin=vector"></noscript>\n<meta name="generator" content="MediaWiki 1.46.0-wmf.17">\n<meta name="referrer" content="origin">\n<meta name="referrer" content="origin-when-cross-origin">\n<meta name="robots" content="max-image-preview:standard">\n<meta name="format-detection" content="telephone=no">\n<meta name="viewport" content="width=1120">\n<meta property="og:title" content="\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0 \xe2\x80\x94 \xd0\x92\xd0\xb8\xd0\xba\xd0\xb8\xd0\xbf\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f">\n<meta property="og:type" content="website">\n<link rel="preconnect" href="//upload.wikimedia.org">\n<link rel="alternate" type="application/x-wiki" title="\xd0\x9f\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x82\xd1\x8c" href="/w/index.php?title=%D0%A3%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%92%D0%B0%D0%BD-%D0%B4%D0%B5%D1%80-%D0%92%D0%B0%D0%B0%D0%BB%D1%8C%D1%81%D0%B0&amp;action=edit">\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">\n<link rel="icon" href="/static/favicon/wikipedia.ico">\n<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="\xd0\x92\xd0\xb8\xd0\xba\xd0\xb8\xd0\xbf\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f (ru)">\n<link rel="EditURI" type="application/rsd+xml" href="//ru.wikipedia.org/w/api.php?action=rsd">\n<link rel="canonical" href="https://ru.wikipedia.org/wiki/%D0%A3%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%92%D0%B0%D0%BD-%D0%B4%D0%B5%D1%80-%D0%92%D0%B0%D0%B0%D0%BB%D1%8C%D1%81%D0%B0">\n<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.ru">\n<link rel="alternate" type="application/atom+xml" title="\xd0\x92\xd0\xb8\xd0\xba\xd0\xb8\xd0\xbf\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f\xc2\xa0\xe2\x80\x94 Atom-\xd0\xbb\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0" href="/w/index.php?title=%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%A1%D0%B2%D0%B5%D0%B6%D0%B8%D0%B5_%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8&amp;feed=atom">\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n<link rel="dns-prefetch" href="auth.wikimedia.org">\n</head>\n<body class="skin-vector-legacy mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5_\xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0 rootpage-\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5_\xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0 skin-vector action-view">\n<div id="mw-aria-live-region" class="mw-aria-live-region" aria-live="polite"></div><div id="mw-page-base" class="noprint"></div>\n<div id="mw-head-base" class="noprint"></div>\n<div id="content" class="mw-body" role="main">\n\t<a id="top"></a>\n\t<div id="siteNotice"><!-- CentralNotice --></div>\n\t<div class="mw-indicators">\n\t</div>\n\t<h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0</span></h1>\n\t<div id="bodyContent" class="vector-body">\n\t\t<div id="siteSub" class="noprint">\xd0\x9c\xd0\xb0\xd1\x82\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb \xd0\xb8\xd0\xb7 \xd0\x92\xd0\xb8\xd0\xba\xd0\xb8\xd0\xbf\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xb8 \xe2\x80\x94 \xd1\x81\xd0\xb2\xd0\xbe\xd0\xb1\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb9 \xd1\x8d\xd0\xbd\xd1\x86\xd0\xb8\xd0\xba\xd0\xbb\xd0\xbe\xd0\xbf\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xb8</div>\n\t\t<div id="contentSub"><div id="mw-content-subtitle"></div></div>\n\t\t<div id="contentSub2"></div>\n\t\t\n\t\t<div id="jump-to-nav"></div>\n\t\t<a class="mw-jump-link" href="#mw-head">\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb9\xd1\x82\xd0\xb8 \xd0\xba \xd0\xbd\xd0\xb0\xd0\xb2\xd0\xb8\xd0\xb3\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8</a>\n\t\t<a class="mw-jump-link" href="#searchInput">\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb9\xd1\x82\xd0\xb8 \xd0\xba \xd0\xbf\xd0\xbe\xd0\xb8\xd1\x81\xd0\xba\xd1\x83</a>\n\t\t<div id="mw-content-text" class="mw-body-content"><div class="mw-content-ltr mw-parser-output" lang="ru" dir="ltr"><p><b>\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xcc\x81\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xcc\x81\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0</b> (<i>\xd0\xb8\xd0\xbb\xd0\xb8</i> \xd1\x83\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xcc\x81\xd0\xbd\xd0\xb8\xd0\xb5 <b>\xd0\x92\xd0\xb0\xd0\xbd \xd0\xb4\xd0\xb5\xd1\x80 \xd0\x92\xd0\xb0\xcc\x81\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0</b><sup id="cite&#95;ref-7" class="reference"><a href="#cite_note-7"><span class="cite-bracket">&#91;</span>\xd0\x9a 1<span class="cite-bracket">&#93;</span></a></sup>)&#160;\xe2\x80\x94 <a href="/wiki/%D0%A3%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5" title="\xd0\xa3\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5">\xd1\x83\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5</a>, \xd1\x81\xd0\xb2\xd1\x8f\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x8e\xd1\x89\xd0\xb5\xd0\xb5 \xd0\xbe\xd1\x81\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb5 <a href="/wiki/%D0%A2%D0%B5%D1%80%D0%BC%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B8%D0%BD%D1%8B" title="\xd0\xa2\xd0\xb5\xd1\x80\xd0\xbc\xd0\xbe\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb0\xd0\xbc\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xb2\xd0\xb5\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb8\xd0\xbd\xd1\x8b">\xd1\x82\xd0\xb5\xd1\x80\xd0\xbc\xd0\xbe\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb0\xd0\xbc\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xb2\xd0\xb5\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb8\xd0\xbd\xd1\x8b</a> \xd0\xb2 \xd0\xbc\xd0\xbe\xd0\xb4\xd0\xb5\xd0\xbb\xd0\xb8 \xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb0 <a href="/wiki/%D0%92%D0%B0%D0%BD-%D0%B4%D0%B5%D1%80-%D0%92%D0%B0%D0%B0%D0%BB%D1%8C%D1%81,_%D0%AF%D0%BD_%D0%94%D0%B8%D0%B4%D0%B5%D1%80%D0%B8%D0%BA" class="mw-redirect" title="\xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81, \xd0\xaf\xd0\xbd \xd0\x94\xd0\xb8\xd0\xb4\xd0\xb5\xd1\x80\xd0\xb8\xd0\xba">\xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0</a>.\n</p><p>\xd0\xa5\xd0\xbe\xd1\x82\xd1\x8f \xd0\xbc\xd0\xbe\xd0\xb4\xd0\xb5\xd0\xbb\xd1\x8c <a href="/wiki/%D0%98%D0%B4%D0%B5%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%B3%D0%B0%D0%B7" title="\xd0\x98\xd0\xb4\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xb3\xd0\xb0\xd0\xb7">\xd0\xb8\xd0\xb4\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb0</a> \xd1\x85\xd0\xbe\xd1\x80\xd0\xbe\xd1\x88\xd0\xbe \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd1\x8b\xd0\xb2\xd0\xb0\xd0\xb5\xd1\x82 \xd0\xbf\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 <a href="/wiki/%D0%A0%D0%B5%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%B3%D0%B0%D0%B7%D1%8B" class="mw-redirect" title="\xd0\xa0\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb3\xd0\xb0\xd0\xb7\xd1\x8b">\xd1\x80\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd1\x85 \xd0\xb3\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2</a> \xd0\xbf\xd1\x80\xd0\xb8 \xd0\xbd\xd0\xb8\xd0\xb7\xd0\xba\xd0\xb8\xd1\x85 <a href="/wiki/%D0%94%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_(%D1%84%D0%B8%D0%B7%D0%B8%D0%BA%D0%B0)" class="mw-redirect" title="\xd0\x94\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 (\xd1\x84\xd0\xb8\xd0\xb7\xd0\xb8\xd0\xba\xd0\xb0)">\xd0\xb4\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f\xd1\x85</a> \xd0\xb8 \xd0\xb2\xd1\x8b\xd1\x81\xd0\xbe\xd0\xba\xd0\xb8\xd1\x85 <a href="/wiki/%D0%A2%D0%B5%D0%BC%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B0_(%D0%B2_%D1%84%D0%B8%D0%B7%D0%B8%D0%BA%D0%B5)" class="mw-redirect" title="\xd0\xa2\xd0\xb5\xd0\xbc\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb0\xd1\x82\xd1\x83\xd1\x80\xd0\xb0 (\xd0\xb2 \xd1\x84\xd0\xb8\xd0\xb7\xd0\xb8\xd0\xba\xd0\xb5)">\xd1\x82\xd0\xb5\xd0\xbc\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb0\xd1\x82\xd1\x83\xd1\x80\xd0\xb0\xd1\x85</a>, \xd0\xb2 \xd0\xb4\xd1\x80\xd1\x83\xd0\xb3\xd0\xb8\xd1\x85 \xd1\x83\xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb8\xd1\x8f\xd1\x85 \xd0\xb5\xd1\x91 \xd1\x81\xd0\xbe\xd0\xbe\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82\xd1\x81\xd1\x82\xd0\xb2\xd0\xb8\xd0\xb5 \xd1\x81 <a href="/wiki/%D0%AD%D0%BA%D1%81%D0%BF%D0%B5%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D1%82" title="\xd0\xad\xd0\xba\xd1\x81\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82">\xd0\xbe\xd0\xbf\xd1\x8b\xd1\x82\xd0\xbe\xd0\xbc</a> \xd0\xb3\xd0\xbe\xd1\x80\xd0\xb0\xd0\xb7\xd0\xb4\xd0\xbe \xd1\x85\xd1\x83\xd0\xb6\xd0\xb5. \xd0\x92 \xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd0\xb8, \xd1\x8d\xd1\x82\xd0\xbe \xd0\xbf\xd1\x80\xd0\xbe\xd1\x8f\xd0\xb2\xd0\xbb\xd1\x8f\xd0\xb5\xd1\x82\xd1\x81\xd1\x8f \xd0\xb2 \xd1\x82\xd0\xbe\xd0\xbc, \xd1\x87\xd1\x82\xd0\xbe <a href="/wiki/%D0%A0%D0%B5%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%B3%D0%B0%D0%B7%D1%8B" class="mw-redirect" title="\xd0\xa0\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb3\xd0\xb0\xd0\xb7\xd1\x8b">\xd1\x80\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb3\xd0\xb0\xd0\xb7\xd1\x8b</a> \xd0\xbc\xd0\xbe\xd0\xb3\xd1\x83\xd1\x82 \xd0\xb1\xd1\x8b\xd1\x82\xd1\x8c \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb2\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbd\xd1\x8b \xd0\xb2 <a href="/wiki/%D0%96%D0%B8%D0%B4%D0%BA%D0%BE%D1%81%D1%82%D1%8C" title="\xd0\x96\xd0\xb8\xd0\xb4\xd0\xba\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c">\xd0\xb6\xd0\xb8\xd0\xb4\xd0\xba\xd0\xbe\xd0\xb5</a> \xd0\xb8 \xd0\xb4\xd0\xb0\xd0\xb6\xd0\xb5 \xd0\xb2 <a href="/wiki/%D0%A2%D0%B2%D1%91%D1%80%D0%B4%D0%BE%D0%B5_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5" class="mw-redirect" title="\xd0\xa2\xd0\xb2\xd1\x91\xd1\x80\xd0\xb4\xd0\xbe\xd0\xb5 \xd1\x81\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x8f\xd0\xbd\xd0\xb8\xd0\xb5">\xd1\x82\xd0\xb2\xd1\x91\xd1\x80\xd0\xb4\xd0\xbe\xd0\xb5 \xd1\x81\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x8f\xd0\xbd\xd0\xb8\xd0\xb5</a>, \xd0\xb0 \xd0\xb8\xd0\xb4\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb5&#160;\xe2\x80\x94 \xd0\xbd\xd0\xb5 \xd0\xbc\xd0\xbe\xd0\xb3\xd1\x83\xd1\x82.\n</p><p>\xd0\x94\xd0\xbb\xd1\x8f \xd0\xb1\xd0\xbe\xd0\xbb\xd0\xb5\xd0\xb5 \xd1\x82\xd0\xbe\xd1\x87\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xbf\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd1\x80\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd1\x85 \xd0\xb3\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2 \xd0\xbf\xd1\x80\xd0\xb8 \xd0\xbd\xd0\xb8\xd0\xb7\xd0\xba\xd0\xb8\xd1\x85 \xd1\x82\xd0\xb5\xd0\xbc\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb0\xd1\x82\xd1\x83\xd1\x80\xd0\xb0\xd1\x85 \xd0\xb1\xd1\x8b\xd0\xbb\xd0\xb0 \xd1\x81\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb0 \xd0\xbc\xd0\xbe\xd0\xb4\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb0 \xd0\x92\xd0\xb0\xd0\xbd-\xd0\xb4\xd0\xb5\xd1\x80-\xd0\x92\xd0\xb0\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xb0, \xd1\x83\xd1\x87\xd0\xb8\xd1\x82\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x8e\xd1\x89\xd0\xb0\xd1\x8f \xd1\x81\xd0\xb8\xd0\xbb\xd1\x8b \xd0\xbc\xd0\xb5\xd0\xb6\xd0\xbc\xd0\xbe\xd0\xbb\xd0\xb5\xd0\xba\xd1\x83\xd0\xbb\xd1\x8f\xd1\x80\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xb2\xd0\xb7\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb4\xd0\xb5\xd0\xb9\xd1\x81\xd1\x82\xd0\xb2\xd0\xb8\xd1\x8f. \xd0\x92 \xd1\x8d\xd1\x82\xd0\xbe\xd0\xb9 \xd0\xbc\xd0\xbe\xd0\xb4\xd0\xb5\xd0\xbb\xd0\xb8 <a href="/wiki/%D0%92%D0%BD%D1%83%D1%82%D1%80%D0%B5%D0%BD%D0%BD%D1%8F%D1%8F_%D1%8D%D0%BD%D0%B5%D1%80%D0%B3%D0%B8%D1%8F" title="\xd0\x92\xd0\xbd\xd1\x83\xd1\x82\xd1\x80\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8f\xd1\x8f \xd1\x8d\xd0\xbd\xd0\xb5\xd1\x80\xd0\xb3\xd0\xb8\xd1\x8f">\xd0\xb2\xd0\xbd\xd1\x83\xd1\x82\xd1\x80\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8f\xd1\x8f \xd1\x8d\xd0\xbd\xd0\xb5\xd1\x80\xd0\xb3\xd0\xb8\xd1\x8f</a> <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="

In [16]:
resp.text[:50]

'<!DOCTYPE html>\n<html class="client-nojs skin-them'

In [18]:
"<table" in resp.text

True

In [20]:
import pandas as pd

In [21]:
pd.read_html(resp.text)

<ipython-input-21-b3c5e1864e98>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(resp.text)

<class 'ImportError'>: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.

In [23]:
%pip install lxml

In [25]:
type(pd.read_html(resp.text))

<ipython-input-25-24a9bd6d47e4>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  type(pd.read_html(resp.text))

list

In [26]:
len(pd.read_html(resp.text))

<ipython-input-26-26943cdf4262>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  len(pd.read_html(resp.text))

3

In [27]:
tables = pd.read_html(resp.text)
tables[0]

<ipython-input-27-57be5fd54d1d>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

                  Вещество  a,  Па·м6·моль−2  b,  10−6 м3·моль−1
0                  Азот N2              1370                 387
1               Аммиак NH3              4225                 371
2                 Аргон Ar              1355                 320
3            Ацетилен C2H2              4516                 522
4                 Бром Br2               975                 591
5         Бромоводород HBr              4500                 442
6              Бутан C4H10              1389                1164
7                 Вода H2O              5537                 305
8               Водород H2              2452                 265
9     Гексафторид серы SF6              7857                 879
10                Гелий He               346                 238
11           Гидразин N2H4               846                 462
12             Кислород O2              1382                 319
13              Криптон Kr              5193                 106
14               Ксенон Xe              4192                 516
15               Метан CH4              2303                 431
16                 Неон Ne               208                 167
17                 Озон O3              3570                 487
18       Окись углерода CO              1472                 395
19             Пропан C3H8               939                 905
20  Сернистый ангидрид SO2              6865                 568
21         Сероводород H2S              4544                 434
22      Углекислый газ CO2              3658                 429
23                 Фтор F2              1171                 290
24         Фтороводород HF              9565                 739
25                Хлор Cl2              6343                 542
26        Хлороводород HCl              3700                 406
27        Циановодород HCN              1129                 881
28               Этан C2H6              5580                 651
29             Этилен C2H4              4612                 582

In [28]:
tables = pd.read_html(
    resp.text, 
    decimal=",", 
    thousands=None,
)
tables[0]

<ipython-input-28-c1968ee0da0d>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(

                  Вещество  a,  Па·м6·моль−2  b,  10−6 м3·моль−1
0                  Азот N2           0.13700                38.7
1               Аммиак NH3           0.42250                37.1
2                 Аргон Ar           0.13550                32.0
3            Ацетилен C2H2           0.45160                52.2
4                 Бром Br2           0.97500                59.1
5         Бромоводород HBr           0.45000                44.2
6              Бутан C4H10           1.38900               116.4
7                 Вода H2O           0.55370                30.5
8               Водород H2           0.02452                26.5
9     Гексафторид серы SF6           0.78570                87.9
10                Гелий He           0.00346                23.8
11           Гидразин N2H4           0.84600                46.2
12             Кислород O2           0.13820                31.9
13              Криптон Kr           0.51930                10.6
14               Ксенон Xe           0.41920                51.6
15               Метан CH4           0.23030                43.1
16                 Неон Ne           0.02080                16.7
17                 Озон O3           0.35700                48.7
18       Окись углерода CO           0.14720                39.5
19             Пропан C3H8           0.93900                90.5
20  Сернистый ангидрид SO2           0.68650                56.8
21         Сероводород H2S           0.45440                43.4
22      Углекислый газ CO2           0.36580                42.9
23                 Фтор F2           0.11710                29.0
24         Фтороводород HF           0.95650                73.9
25                Хлор Cl2           0.63430                54.2
26        Хлороводород HCl           0.37000                40.6
27        Циановодород HCN           1.12900                88.1
28               Этан C2H6           0.55800                65.1
29             Этилен C2H4           0.46120                58.2