In [10]:
import requests

In [14]:
requests.get("https://ya.ru")

In [15]:
resp = requests.get("https://ya.ru")

In [17]:
resp.content

b'<!doctype html><html prefix="og: http://ogp.me/ns#" lang="en"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n    <link rel="shortcut icon" href="https://yastatic.net/s3/home-static/_/a5/a557b72322add07a6b41fc8f71cfffc8.png" sizes="16x16">\n    <link rel="shortcut icon" href="https://yastatic.net/s3/home-static/_/92/929b10d17990e806734f68758ec917ec.png" sizes="32x32">\n    <link rel="shortcut icon" href="https://yastatic.net/s3/home-static/_/7c/7ccfee6f1e81b14c5bef535d1ad7b7e0.png" sizes="192x192">\n    <link rel="apple-touch-icon" href="https://yastatic.net/s3/home-static/_/75/759c668aa6747fee858fb5ae0c207474.png" sizes="152x152">\n    <link rel="apple-touch-icon" href="https://yastatic.net/s3/home-static/_/90/9034470dfcb0bea0db29a281007b8a38.png" sizes="180x180">\n<title data-react-helmet="true">Are you not a robot?</title><meta data-react-helmet="true" property="og:title" content="Yandex"><meta data-react-helmet="true" property="og:description" content="Finds everything"><meta data-react-helmet="true" property="og:image" content="https://yastatic.net/s3/home-static/_/90/9034470dfcb0bea0db29a281007b8a38.png"><link rel="stylesheet" href="/captcha_smart.c1f6a7cf8d410e04e643.min.css?k=1770297641484"><style>@media only screen and (min-width:651px) and (prefers-color-scheme:light){body{background-image:url(\'https://captcha-backgrounds.s3.yandex.net/static/default-background.jpg\')}}@media only screen and (min-width:651px) and (prefers-color-scheme:dark){body{background-image:url(\'https://captcha-backgrounds.s3.yandex.net/static/dark-background.jpg\')}}@media (prefers-color-scheme:light){.LogoLink{background-image:url(\'https://cdnrhkgfkkpupuotntfj.svc.cdn.yandex.net/yandexlogo.svg\')}.Theme_root_default{--smart-captcha-background-color:#fff;--checkbox-captcha-error-color:#f33;--checkbox-captcha-border:1px solid rgba(0,0,0,0.15);--checkbox-captcha-border-radius:11px;--anchor-background-color:#fff;--anchor-background-color-error:rgba(255,51,51,0.12);--anchor-background-color-checked:#5282ff;--anchor-check-mark-color:#fff;--anchor-border:2px solid #ccc;--spin-view-captcha-border-color:#5c81d1;--advanced-captcha-border-radius:11px;--advanced-captcha-image-preview-background-color:rgba(0,0,0,0.05);--textinput-border:2px solid rgba(0,0,0,0.1);--textinput-border-focused:2px solid rgba(0,0,0,0.3);--textinput-view-default-fill-color-base:#fff;--advanced-captcha-tooltip-background-color:#adafb6;--link-view-default-typo-color-base:#04b;--color-typo-ghost:rgba(0,0,0,0.3);--color-base:#000;--color-typo-primary:var(--color-base);--button-view-action-typo-color-base:#fff;--button-view-action-fill-color-base:#6b94f7;--button-view-action-fill-color-hovered:#5c81d1}}@media (prefers-color-scheme:dark){.LogoLink{background-image:url(\'https://cdnrhkgfkkpupuotntfj.svc.cdn.yandex.net/yandexlogo.svg\')}.Theme_root_default{--smart-captcha-background-color:#313036;--checkbox-captcha-error-color:#f33;--checkbox-captcha-border:1px solid #d9d9d9;--checkbox-captcha-border-radius:11px;--anchor-background-color:#313036;--anchor-background-color-error:rgba(255, 51, 51, 0.12);--anchor-background-color-checked:#5c81d1;--anchor-check-mark-color:#fff;--anchor-border:2px solid #6b6b72;--spin-view-captcha-border-color:#5c81d1;--advanced-captcha-border-radius:24px;--advanced-captcha-image-preview-background-color:#414148;--textinput-border:2px solid #95969a;--textinput-border-focused:2px solid #adafb6;--textinput-view-default-fill-color-base:#6e6e73;--advanced-captcha-tooltip-background-color:#adafb6;--link-view-default-typo-color-base:red;--color-typo-ghost:var(--color-typo-primary);--color-base:#dfdfe0;--color-typo-primary:var(--color-base);--button-view-action-typo-color-base:#fff;--button-view-action-fill-color-base:#6b94f7;--button-view-action-fill-color-hovered:#5c81d1}}</style><div id="root"><div class="Theme Theme_color_yandex-default Theme_root_default"><main><div class="Container"><div class="Spacer" style="padding-bottom:40px"><a href="https://www.yandex.com" aria-label="Yandex" class="Link Link_view_default LogoLink"></a></div><form method="POST" action="/checkcaptcha?key=c20a06ee-b1bf1567-1108bac2-79f31a53_2/1772442384/fbbda98eac49df83b8b35ae3d9cc3e7f_2ab28663a1153b37d9830e4e5ba94aee&mt=DA6AB9C25837C1767E4C5C258ED640BCEAAE2EAC3E7C71833B4091F86C851A0408F865BDA76C6CC5446552131CA89F6CB9E57E0A64516519AFE77C85DD48BD0531B7679CA7C9787E06A1F77F66765A05C75896793B06F78EFF604EB2A300F6CF2788B528FDA0C4CB04340E2CDF8D070C7A93341A3EF59CA7E4700969D29803BB78313C0C0875A80FE60B7B5EE8A6F97829E9A34E2B957715188F236B8D7A4353024EB5D17C6D49457B1549EF262EED95A0CD733DABBCC56488C699C48A72BD861B8EEB8E8FC28ECA9763AF43D6A04F51F4946ABCD1013439B8AA&retpath=aHR0cHM6Ly95YS5ydS8_bnI9MSZyZWRpcmVjdF90cz0xNzcyNDQyMzg0LjAwMDAw_9fcf7c390ffa5f97069d300f52794515&u=8266130459809964096&s=b125f05796e3a6344163e44ba6b9bf29" id="checkbox-captcha-form"><div class="Spacer" style="padding-bottom:16px"><h1 class="Text Text_weight_medium Text_typography_headline-s">Please confirm that you and not a robot are sending requests</h1></div><div class="Spacer" style="padding-bottom:16px"><span class="Text Text_weight_regular Text_typography_body-long-m">We&#x27;re sorry, but it looks like requests sent from your device are automated.\xc2\xa0 \xc2\xa0<a href="https://yandex.com/support/smart-captcha/problems.html?form-unique_key=8266130459809964096&form-fb-hint=8.47" target="_blank" class="Link Link_view_default">Why might this happen?</a></span></div><noscript><span class="Text Text_color_alert Text_weight_medium Text_typography_body-long-m">JavaScript is disabled. After checkbox you will have additional check.\xc2\xa0<a href="https://yandex.com/support/common/browsers-settings/browsers-java-js-settings.html" target="_blank" class="Link Link_view_default">How to enable JavaScript?</a></span></noscript><div class="Spacer Spacer_auto-gap_bottom" style="padding-top:40px;padding-bottom:40px"><div class="CheckboxCaptcha CheckboxCaptcha_first_letter_highlighted" data-testid="checkbox-captcha"><div class="CheckboxCaptcha-Inner"><div class="CheckboxCaptcha-Anchor"><input type="button" id="js-button" class="CheckboxCaptcha-Button" aria-checked="false" aria-labelledby="checkbox-label" aria-describedby="checkbox-description" role="checkbox"><noscript><input type="submit" class="CheckboxCaptcha-Button" aria-checked="false" aria-labelledby="checkbox-label" aria-describedby="checkbox-description" role="checkbox"></noscript><div class="CheckboxCaptcha-Checkbox" data-checked="false"><svg class="SvgIcon CheckIcon" width="24" height="24" viewBox="0 0 24 25" fill="none"><path d="M4 12.5L9.5 18.5L20 6.5" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"></path></svg></div></div><div class="CheckboxCaptcha-Label"><span class="Text Text_weight_regular Text_typography_control-xxl CheckboxCaptcha-LabelText"><span id="checkbox-label">I&#x27;m not a robot\xc2\xa0</span></span><span class="Text Text_weight_regular Text_typography_control-l CheckboxCaptcha-SecondaryText"><span id="checkbox-description">Press to continue</span></span></div></div><div class="Text Text_color_ghost Text_weight_regular Text_typography_control-s CaptchaLinks CheckboxCaptcha-Links"><button aria-label="Show links" aria-pressed="false" type="button" class="CaptchaButton CaptchaButton_view_clear CaptchaButton_size_m CaptchaLinks-ToggleButton CaptchaLinks-ToggleButton_checkbox"><svg class="SvgIcon" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 18.5625C15.1766 18.5625 18.5625 15.1766 18.5625 11C18.5625 6.82334 15.1766 3.4375 11 3.4375C6.82334 3.4375 3.4375 6.82334 3.4375 11C3.4375 15.1766 6.82334 18.5625 11 18.5625ZM11 20.625C16.3157 20.625 20.625 16.3157 20.625 11C20.625 5.68426 16.3157 1.375 11 1.375C5.68426 1.375 1.375 5.68426 1.375 11C1.375 16.3157 5.68426 20.625 11 20.625ZM8.85528 6.24171C9.44645 5.75611 10.2222 5.46546 11 5.46546C12.6736 5.46546 14.2167 6.59336 14.2167 8.409C14.2167 8.92624 14.1095 9.43266 13.8078 9.92185C13.5213 10.3865 13.1023 10.7646 12.6048 11.1132C12.3057 11.3227 12.1569 11.4663 12.0839 11.5642C12.0312 11.6348 12.0312 11.661 12.0313 11.686L12.0313 11.6872C12.0313 12.2567 11.5695 12.7185 11 12.7185C10.4305 12.7185 9.96876 12.2567 9.96876 11.6872C9.96876 10.5945 10.7163 9.9179 11.4214 9.42397C11.806 9.15451 11.9732 8.9675 12.0523 8.83924C12.1163 8.73548 12.1542 8.62111 12.1542 8.409C12.1542 7.9976 11.8192 7.52796 11 7.52796C10.718 7.52796 10.401 7.6411 10.1644 7.83546C9.9342 8.02457 9.84579 8.22978 9.84579 8.409C9.84579 8.97854 9.38408 9.44025 8.81454 9.44025C8.24499 9.44025 7.78329 8.97854 7.78329 8.409C7.78329 7.48351 8.25771 6.73257 8.85528 6.24171ZM11 16.5C11.7594 16.5 12.375 15.8844 12.375 15.125C12.375 14.3656 11.7594 13.75 11 13.75C10.2406 13.75 9.625 14.3656 9.625 15.125C9.625 15.8844 10.2406 16.5 11 16.5Z" fill="currentColor"></path></svg></button><div class="CaptchaLinks-Links"><a color="secondary" target="_blank" href="https://yandex.cloud/en/services/smartcaptcha?utm_source=captcha&amp;utm_medium=chbx&amp;utm_campaign=security" class="Link Link_color_secondary Link_view_captcha CaptchaLinks-ServiceLink">SmartCaptcha by Yandex Cloud</a></div></div></div></div><input type="hidden" name="rdata"><input type="hidden" name="pdata" value="eyJwb3dDYWxjVGltZSI6LTEsInBvd05vbmNlIjoiIiwicG93UHJlZml4IjoiIn0="><input type="hidden" name="tdata"><input type="hidden" name="picasso"></form><span class="Text Text_color_ghost Text_weight_regular Text_typography_control-xs">If you have any problems, please use the\xc2\xa0<a href="https://yandex.com/support/smart-captcha/problems.html?form-unique_key=8266130459809964096&form-fb-hint=8.47" target="_blank" class="Link Link_view_default">feedback form</a></span><div class="Spacer" style="padding-top:10px"><span class="Text Text_color_ghost Text_weight_regular Text_typography_control-xxs"><span data-testid="unique-key">8266130459809964096</span>:<span data-testid="timestamp">1772442384</span></span></div></div></main></div></div><script>let button=document.getElementById("js-button");button.addEventListener("click",(function t(n){window.__JS_BUTTON_CLICKED__=!0,this.removeEventListener("click",t,!1)}),!1),window.onerror=function(t,n){0===n.indexOf(window.location.origin+"/captcha_smart.c1f6a7cf8d410e04e643.js")&&(button.type="submit",window.Ya)&&window.Ya.Rum&&window.Ya.Rum.logEventString&&window.Ya.Rum.logEventString("js_fail_force_submit_type",t,{page:"checkbox"})}</script> <script>window.__SSR_DATA__={url:"/en/checkbox",invalid:"no",formAction:"/checkcaptcha?key=c20a06ee-b1bf1567-1108bac2-79f31a53_2/1772442384/fbbda98eac49df83b8b35ae3d9cc3e7f_2ab28663a1153b37d9830e4e5ba94aee&mt=DA6AB9C25837C1767E4C5C258ED640BCEAAE2EAC3E7C71833B4091F86C851A0408F865BDA76C6CC5446552131CA89F6CB9E57E0A64516519AFE77C85DD48BD0531B7679CA7C9787E06A1F77F66765A05C75896793B06F78EFF604EB2A300F6CF2788B528FDA0C4CB04340E2CDF8D070C7A93341A3EF59CA7E4700969D29803BB78313C0C0875A80FE60B7B5EE8A6F97829E9A34E2B957715188F236B8D7A4353024EB5D17C6D49457B1549EF262EED95A0CD733DABBCC56488C699C48A72BD861B8EEB8E8FC28ECA9763AF43D6A04F51F4946ABCD1013439B8AA&retpath=aHR0cHM6Ly95YS5ydS8_bnI9MSZyZWRpcmVjdF90cz0xNzcyNDQyMzg0LjAwMDAw_9fcf7c390ffa5f97069d300f52794515&u=8266130459809964096&s=b125f05796e3a6344163e44ba6b9bf29",captchaKey:"c20a06ee-b1bf1567-1108bac2-79f31a53_2/1772442384/fbbda98eac49df83b8b35ae3d9cc3e7f_2ab28663a1153b37d9830e4e5ba94aee",imageSrc:"",taskImageSrc:"",task:"",voiceSrc:"",introSrc:"",aesKey:"ZfGT3yaZtwVnu0W6ou+US1FqEcP5aztADPXL1dENcmw=",aesSign:"1_1772442384_12825038989818900276_f554ad6f4d9eab0bb0002706293ef4ed",reqId:"1772442384113731-7087163635963322721-balancer-l7leveler-kubr-yp-klg-105-BAL",uniqueKey:"8266130459809964096",powPrefix:"743D313737323434323338343B703D36653635633461332D39336261333331322D61316162366231612D62653435663338333B633D31353B643D34343341344543423039454446464436363642333933344534424231463738413B",powComplexity:"15",sitekey:"",smartCaptchaHost:"",timestamp:"1772442384",ogTitle:"Yandex",ogDescription:"Finds everything",ogImage:"https://yastatic.net/s3/home-static/_/90/9034470dfcb0bea0db29a281007b8a38.png",support:"https://yandex.com/support/smart-captcha/problems.html?form-unique_key=8266130459809964096&form-fb-hint=8.47",firstLetterHighlighted:"",linksVisible:"yes",automaticPrecheck:"",searchApiVisible:"no"}</script><script src="/captcha_smart_error.c1f6a7cf8d410e04e643.min.js?k=1770297641484" crossorigin=""></script><script src="/captcha_smart_react.min.js?k=1770297641484" crossorigin=""></script><script src="/captcha_smart.c1f6a7cf8d410e04e643.js?k=1770297641484" crossorigin=""></script><script>!function(e,n,t,a,c){e.ym=e.ym||function(){(e.ym.a=e.ym.a||[]).push(arguments)},e.ym.l=+new Date,a=n.createElement(t),c=n.getElementsByTagName(t)[0],a.async=1,a.src="https://mc.yandex.ru/metrika/tag.js",c.parentNode.insertBefore(a,c)}(window,document,"script"),ym(10630330,"init",{clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0,ut:"noindex",params:{req_id:"1772442384113731-7087163635963322721-balancer-l7leveler-kubr-yp-klg-105-BAL",unique_key:"8266130459809964096"}})</script><noscript><div><img src="https://mc.yandex.ru/watch/10630330?ut=noindex" style="position:absolute;left:-9999px" alt=""></div></noscript><div><img src="https://adfstat.yandex.ru/captcha?req_id=1772442384113731-7087163635963322721-balancer-l7leveler-kubr-yp-klg-105-BAL&unique_key=8266130459809964096" style="position:absolute;left:-9999px" alt=""></div></html>'

In [21]:
list("absприветα")

['a', 'b', 's', 'п', 'р', 'и', 'в', 'е', 'т', 'α']

In [22]:
url = "https://ru.wikipedia.org/wiki/Уравнение_Ван-дер-Ваальса"
# Если копировать
# "https://ru.wikipedia.org/wiki/%D0%A3%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%92%D0%B0%D0%BD-%D0%B4%D0%B5%D1%80-%D0%92%D0%B0%D0%B0%D0%BB%D1%8C%D1%81%D0%B0"

In [24]:
van_der_vaals_eq_wiki_page = requests.get(url).content

In [30]:
van_der_vaals_eq_wiki_page[:35]

b'<!DOCTYPE html>\n<html class="client'

In [33]:
list(b'<!DOCTYPE ')

[60, 33, 68, 79, 67, 84, 89, 80, 69, 32]

In [34]:
list(b'123456')

[49, 50, 51, 52, 53, 54]

In [40]:
van_der_vaals_eq_wiki_page = requests.get(url).text
van_der_vaals_eq_wiki_page[:25]

'<!DOCTYPE html>\n<html cla'

In [47]:
%pip install lxml pandas

In [48]:
import pandas as pd

In [50]:
type(pd.read_html(van_der_vaals_eq_wiki_page))

<ipython-input-50-75f69e52afa8>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  type(pd.read_html(van_der_vaals_eq_wiki_page))

list

In [51]:
len(pd.read_html(van_der_vaals_eq_wiki_page))

<ipython-input-51-6570555ddbb2>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  len(pd.read_html(van_der_vaals_eq_wiki_page))

3

In [60]:
tables = pd.read_html(
    van_der_vaals_eq_wiki_page, 
    decimal=",",
    thousands=None,
)
df = tables[0]
df.head()

<ipython-input-60-dcaa2e13c2f0>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(

        Вещество  a,  Па·м6·моль−2  b,  10−6 м3·моль−1
0        Азот N2            0.1370                38.7
1     Аммиак NH3            0.4225                37.1
2       Аргон Ar            0.1355                32.0
3  Ацетилен C2H2            0.4516                52.2
4       Бром Br2            0.9750                59.1

In [66]:
df["Вещество"].str.rsplit(" ", n=1, expand=True)

                     0      1
0                 Азот     N2
1               Аммиак    NH3
2                Аргон     Ar
3             Ацетилен   C2H2
4                 Бром    Br2
5         Бромоводород    HBr
6                Бутан  C4H10
7                 Вода    H2O
8              Водород     H2
9     Гексафторид серы    SF6
10               Гелий     He
11            Гидразин   N2H4
12            Кислород     O2
13             Криптон     Kr
14              Ксенон     Xe
15               Метан    CH4
16                Неон     Ne
17                Озон     O3
18      Окись углерода     CO
19              Пропан   C3H8
20  Сернистый ангидрид    SO2
21         Сероводород    H2S
22      Углекислый газ    CO2
23                Фтор     F2
24        Фтороводород     HF
25                Хлор    Cl2
26        Хлороводород    HCl
27        Циановодород    HCN
28                Этан   C2H6
29              Этилен   C2H4

In [70]:
df_with_formula = df.copy()
df_with_formula[["Название", "Формула"]] = \
    df["Вещество"].str.rsplit(" ", n=1, expand=True)
df_with_formula.drop(columns=["Вещество"], inplace=True)
# df_with_formula = df_with_formula.drop(columns=["Вещество"])

df_with_formula.head()

   a,  Па·м6·моль−2  b,  10−6 м3·моль−1  Название Формула
0            0.1370                38.7      Азот      N2
1            0.4225                37.1    Аммиак     NH3
2            0.1355                32.0     Аргон      Ar
3            0.4516                52.2  Ацетилен    C2H2
4            0.9750                59.1      Бром     Br2

In [84]:
list(df_with_formula.columns)[2:] \
    + list(df_with_formula.columns)[:2]

['Название', 'Формула', 'a,  Па·м6·моль−2', 'b,  10−6 м3·моль−1']

In [89]:
df_with_formula_pretty = df_with_formula[
    list(df_with_formula.columns)[2:]
    + list(df_with_formula.columns)[:2]
]
df_with_formula_pretty.head()

   Название Формула  a,  Па·м6·моль−2  b,  10−6 м3·моль−1
0      Азот      N2            0.1370                38.7
1    Аммиак     NH3            0.4225                37.1
2     Аргон      Ar            0.1355                32.0
3  Ацетилен    C2H2            0.4516                52.2
4      Бром     Br2            0.9750                59.1

In [1]:
%pip install pubchempy ssl

In [2]:
import pubchempy

In [5]:
pubchempy.get_compounds(783)

<class 'NameError'>: name 'HTTPSHandler' is not defined

In [3]:
pubchempy.get_compounds("H2", "formula")

<class 'NameError'>: name 'HTTPSHandler' is not defined